### ISSUE TITLE
Typo in the dashboard

### ISSUE THREAD

**Issue by Sealdolphin** [marcsello/ezotv#7]
Az `Információk` pont alatt összeszedett typo-k:
 - megváltoztatánál -> megváltoztatásnál [3. bekezdés](https://github.com/marcsello/ezotv/blob/9b69cb97f3f097047f0c9dfc070d18fd214b826c/ezotv/templates/dashboard.html#L119)
 - Ezesetben -> Ez esetben [3. bekezdés](https://github.com/marcsello/ezotv/blob/9b69cb97f3f097047f0c9dfc070d18fd214b826c/ezotv/templates/dashboard.html#L119)
 - Ha csak a jelszót -> Ha csak jelszót [4. bekezdés](https://github.com/marcsello/ezotv/blob/9b69cb97f3f097047f0c9dfc070d18fd214b826c/ezotv/templates/dashboard.html#L120)
 - majd csatlakozni a -> majd csatlakozni, [5. bekezdés](https://github.com/marcsello/ezotv/blob/9b69cb97f3f097047f0c9dfc070d18fd214b826c/ezotv/templates/dashboard.html#L121)

**Comment by marcsello** [comment]
Köszi szépen! :)
